version: '3'

services:
  db:
    container_name: mysql_compose
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - "mysql_volume:/var/lib/mysql"


volumes:
  mysql_volume: